### ISSUE TITLE
The website crashed?

### ISSUE THREAD

**Issue by colinxu2020** [CloudLoaderMC/CloudLoader#2]
## I can't use Discord due to our government's limit.

![image](https://i.mcmod.cn/editor/upload/20221226/1672047029_104322_eNYm.png)

![image](https://i.mcmod.cn/editor/upload/20221226/1672047161_104322_mjjj.png)

Can you fix it?

**Comment by DevReaper0** [comment]
I believe it should be fixed now. Let me know if there are any other issues.

**Comment by colinxu2020** [comment]
![image](https://i.mcmod.cn/editor/upload/20221227/1672114083_104322_uVen.png)
This appears to be fixed, but here's a new problem like the image.
@DaRubyMiner360

**Comment by colinxu2020** [comment]
I tested it again and this time it went in successfully, why is that?

**Comment by colinxu2020** [comment]
This looks like a probability problem and can't get in again

**Comment by colinxu2020** [comment]
![image](https://i.mcmod.cn/editor/upload/20221227/1672114424_104322_FihJ.png)
new problem.

**Comment by colinxu2020** [comment]
![image](https://i.mcmod.cn/editor/upload/20221227/1672114470_104322_VvMl.png)
new new problem

**Comment by colinxu2020** [comment]
Can you give me an installer for 1.19.2? I went to the official website just to obtain this.

**Comment by DevReaper0** [comment]
Not sure about the Cloudflare error (I think that should be as well), but the problems should be fixed.
