### ISSUE TITLE
How did I get the installer?

### ISSUE THREAD

**Issue by colinxu2020** [CloudLoaderMC/CloudLoader#3]
I can't find it in the website.

**Comment by colinxu2020** [comment]
And I can't build it my myself.If I use the installJar tasks in this project.It will told me that the server return ststus502.If I use build task in CloudInstaller project.It will cause a error.

**Comment by colinxu2020** [comment]
Aaa.I get a build success with "installerJar"..But I still didn't know  how did I merge it with the origin client.

**Comment by DevReaper0** [comment]
Right now, Cloud isn't ready for usage and crashes on startup so there aren't any binaries available. The installer also needs a metadata server to be running but it requires a version to be published. I'll add instructions and links once everything's ready for the first beta release.

**Comment by colinxu2020** [comment]
Ok.But I use forge_client task now.And success enter the game with the cloud.(No Mods)

**Comment by colinxu2020** [comment]
Crash with TR because fabric api version is so old.

**Comment by DevReaper0** [comment]
Right now, Cloud's not in a usable state yet. It's getting closer (not yet committed) but there's still some problems with mappings not being found by Fabric.
